### PR TITLE
Build57

### PR DESCRIPTION
**Pull request by christophsax**
Adds mac and win binaries (addressing #12)

### CODE REVIEW

**Review by eddelbuettel — APPROVED** [review]
Looks good!  I just made one micro-edit just completing one sentence and adding a full stop at another.

**Comment by eddelbuettel** [comment]
If that micro-edit is ok by you I'd be happy to merge.

**Comment by eddelbuettel** [comment]
Shall I just pile Linux charges into the same PR?  I have the 64 bit binary.  I have to think where i would get
- a 32 bit binary from, or we maybe decide it is 2021 and skip 32 bit as nobody is running it anymore
- an armv7l binary from as I do not recall right now what magic we did to build it last time

**Comment by eddelbuettel** [comment]
> I finally got myself onto a Debian porter box of the arm architecture with a armhf chroot a

Apparently I used Debian resources.  How crafty of younger me.

**Comment by christophsax** [comment]
Get rid of 32 bit seems perfectly good to me. If there are such users, they can use the old binaries (which will still be accessible).

**Comment by eddelbuettel** [comment]
Should I put the arm and linux binaries into this PR or create a new one?  

```sh
edd@rob:~/git/x13prebuilt/v1.1.57(build57)$ git add linux/
edd@rob:~/git/x13prebuilt/v1.1.57(build57)$ git st
On branch build57
Your branch is up to date with 'origin/build57'.

Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
        new file:   linux/64/x13ashtml
        new file:   linux/armv7l/x13ashtml
        new file:   linux/buildScript.sh

edd@rob:~/git/x13prebuilt/v1.1.57(build57)$ 
```

**Comment by christophsax** [comment]
Both is fine. We can also merge this and do another one?

**Comment by eddelbuettel** [comment]
I just stick it in -- then we have one PR for all of 1.1.57.

**Pull request merged**
