### PR TITLE
New built christoph

### PR DESCRIPTION
**Pull request by christophsax**

### CODE REVIEW

**Comment by christophsax** [comment]
There is a new build [out there](https://www.census.gov/srd/www/x13as/x13down_unix.html) (1.1.39). I updated win and built the new mac version.

But I guess I have to update seasonal first, as the new build produces a file which breaks it.

**Comment by eddelbuettel** [comment]
I can update Linux builds if you want me to.

**Comment by christophsax** [comment]
I guess I can also do the standard linux builds on Ubuntu as well, but not the armv builds. But then it is perhaps not really necessary to have them updated at all?

**Comment by eddelbuettel** [comment]
Maybe I wasn't awake enough yet :)     I see that they are in your branch already. 

Remind me again:  were those downloads from Census, or did we build them?   In any event this looks weird:

```
edd@max:~/git/x13prebuilt(new-built-christoph)$ v1.1.39/linux/64/x13ashtml -v

 X-13ARIMA-SEATS Seasonal Adjustment Program
 Version Number 1.1 Build 26
 Execution began  Apr 30, 2017  08.02.14 

 ERROR: Must specify either an input specification file name
        (-i infile or infile) or an input metafile name (-m metafile).

        See Section 2 of the X-13ARIMA-SEATS Reference Manual for more
        information on how to run X-13ARIMA-SEATS.
edd@max:~/git/x13prebuilt(new-built-christoph)$ 
```

Should be '1.1 Build 39' in that branch, no?

**Comment by christophsax** [comment]
No, sorry, I haven't done them *yet*, but I can do them. These are still the old ones, sorry.

**Comment by christophsax** [comment]
Only mac and window updated so far.

**Comment by christophsax** [comment]
My first attempt to do something like this, but both builds seem to be fine.

So we are almost good. Open questions:

- [ ] What to do with the `armv` build? Update or not? 
- [ ] Shall we put the historic `windows`, `osx` and `linux` directory in a folder with version number or wait for another year?

    plus: Stops confusing people, by letting them think these are the latest versions.
   minus: Our first version of x13binary will not work anymore.

**Comment by eddelbuettel** [comment]
Awesome on the 32bit build. I was just about to go off and find an old laptop of mine :)  And  I should be able to find the Debian machine I have access to and rebuild there.  

Not sure about the directory cleanup. I am torn.  I hate to break things but the current design is muddled.  Maybe it is time...

**Comment by christophsax** [comment]
I found an old AWS image that I could use... 😄 

Just saw that the armv7l built should probably go into an `armv7l` folder, right?

**Comment by eddelbuettel** [comment]
What do we use again to probe for OS?  I am on the box now:

```
edd@abel:~$ uname -a
Linux abel 3.16.0-4-armmp-lpae #1 SMP Debian 3.16.39-1+deb8u2 (2017-03-07) armv7l GNU/Linux
edd@abel:~$ 
```

but yes -- `armv7l` appears to be its architecture label.

**Comment by christophsax** [comment]
: ${R_HOME=$(R RHOME)}
sysname=$(${R_HOME}/bin/Rscript -e 'cat(Sys.info()["sysname"])')
if [ ${sysname} == "Linux" ]; then
    platform="linux"
    arch=$(uname -m)
    if [ "${arch}" = "x86_64" ]; then
        flavour="64"
    elif [ "${arch}" = "i686" ]; then
        flavour="32"
    elif [ "${arch}" = "armv7l" ]; then
        flavour="armv7l"
    else
        echo "Unknown architecture: ${arch}. Exiting."
        exit -1
    fi
elif [ ${sysname} == "Darwin" ]; then
    platform="osx"
else
    platform=${sysname}
    echo "Unusual platform: ${sysname}"
    echo "For this platform, there are currently no binaries of X-13ARIMA-SEATS"
    echo "available. If you have binaries or building scripts, you are invited"
    echo "to contribute to the project."
    echo "Visit: https://github.com/x13org/x13prebuilt"
    exit 0
fi

**Comment by eddelbuettel** [comment]
That's recursive.  What does `Sys.info()` call ?   ;-)

`Sys.info()`  ends up in C code calling `uname(&name)` filling structure `name`.  Pretty sure that will be the same string.

**Comment by eddelbuettel** [comment]
New push by me with armv7l binary, and removing stray old binary

**Comment by christophsax** [comment]
nice! I am merging this into master, so we can test `x13binary`.

**Pull request merged**
